"""empty message

Revision ID: 400002796312
Revises: 4fa33d5ea997
Create Date: 2023-07-05 22:33:12.702751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400002796312'
down_revision = '4fa33d5ea997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watermark_image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('watermark_image_url')

    # ### end Alembic commands ###
