"""empty message

Revision ID: 4fa33d5ea997
Revises: f224c46b3815
Create Date: 2023-07-05 22:28:59.627351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa33d5ea997'
down_revision = 'f224c46b3815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auteur', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('auteur')

    # ### end Alembic commands ###
