"""empty message

Revision ID: 8865eb46e51a
Revises: 
Create Date: 2023-06-18 15:22:40.833430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8865eb46e51a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contributeur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contributeur_admin',
    sa.Column('contributeur_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['contributeur_id'], ['contributeur.id'], )
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('taille', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATED', 'REJECTED', name='upload_status'), nullable=True),
    sa.Column('payment_required', sa.Boolean(), nullable=True),
    sa.Column('contributeur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributeur_id'], ['contributeur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.String(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur_admin',
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], )
    )
    op.create_table('utilisateur_contributeur',
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('contributeur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributeur_id'], ['contributeur.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], )
    )
    op.create_table('utilisateur_image',
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateur_image')
    op.drop_table('utilisateur_contributeur')
    op.drop_table('utilisateur_admin')
    op.drop_table('paiement')
    op.drop_table('image')
    op.drop_table('contributeur_admin')
    op.drop_table('utilisateur')
    op.drop_table('contributeur')
    op.drop_table('admin')
    # ### end Alembic commands ###
