"""empty message

Revision ID: 8e4e3312e0e2
Revises: d085186c1592
Create Date: 2023-06-18 13:49:09.369295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e4e3312e0e2'
down_revision = 'd085186c1592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'CONTRIBUTOR', name='user_role'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
