"""empty message

Revision ID: ab142786be00
Revises: 5ffd84093fd2
Create Date: 2023-06-14 01:31:41.413733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab142786be00'
down_revision = '5ffd84093fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('paiement_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateur_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('paiement_owner_id_fkey', 'utilisateur', ['owner_id'], ['id'])
        batch_op.drop_column('utilisateur_id')

    # ### end Alembic commands ###
