"""empty message

Revision ID: bd4be1bda45c
Revises: 670cbef76e43
Create Date: 2023-06-22 12:10:22.403413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4be1bda45c'
down_revision = '670cbef76e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributeur_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contributeur.id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin.id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('contributeur_admin_contributeur_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('contributeur_admin_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contributeur', ['contributeur.id'], ['id'])
        batch_op.create_foreign_key(None, 'admin', ['admin.id'], ['id'])
        batch_op.drop_column('admin_id')
        batch_op.drop_column('contributeur_id')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    with op.batch_alter_table('utilisateur_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur.id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin.id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('utilisateur_admin_admin_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('utilisateur_admin_utilisateur_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin', ['admin.id'], ['id'])
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateur.id'], ['id'])
        batch_op.drop_column('admin_id')
        batch_op.drop_column('utilisateur_id')

    with op.batch_alter_table('utilisateur_contributeur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur.id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contributeur.id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('utilisateur_contributeur_contributeur_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('utilisateur_contributeur_utilisateur_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contributeur', ['contributeur.id'], ['id'])
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateur.id'], ['id'])
        batch_op.drop_column('contributeur_id')
        batch_op.drop_column('utilisateur_id')

    with op.batch_alter_table('utilisateur_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur.id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('utilisateur_image_utilisateur_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'utilisateur', ['utilisateur.id'], ['id'])
        batch_op.drop_column('utilisateur_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('utilisateur_image_utilisateur_id_fkey', 'utilisateur', ['utilisateur_id'], ['id'])
        batch_op.drop_column('utilisateur.id')

    with op.batch_alter_table('utilisateur_contributeur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contributeur_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('utilisateur_contributeur_utilisateur_id_fkey', 'utilisateur', ['utilisateur_id'], ['id'])
        batch_op.create_foreign_key('utilisateur_contributeur_contributeur_id_fkey', 'contributeur', ['contributeur_id'], ['id'])
        batch_op.drop_column('contributeur.id')
        batch_op.drop_column('utilisateur.id')

    with op.batch_alter_table('utilisateur_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('utilisateur_admin_utilisateur_id_fkey', 'utilisateur', ['utilisateur_id'], ['id'])
        batch_op.create_foreign_key('utilisateur_admin_admin_id_fkey', 'admin', ['admin_id'], ['id'])
        batch_op.drop_column('admin.id')
        batch_op.drop_column('utilisateur.id')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('contributeur_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contributeur_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('contributeur_admin_admin_id_fkey', 'admin', ['admin_id'], ['id'])
        batch_op.create_foreign_key('contributeur_admin_contributeur_id_fkey', 'contributeur', ['contributeur_id'], ['id'])
        batch_op.drop_column('admin.id')
        batch_op.drop_column('contributeur.id')

    # ### end Alembic commands ###
