"""empty message

Revision ID: d085186c1592
Revises: f151f237c788
Create Date: 2023-06-18 12:56:23.429642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd085186c1592'
down_revision = 'f151f237c788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taille', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('format', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('orientation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('orientation')
        batch_op.drop_column('width')
        batch_op.drop_column('height')
        batch_op.drop_column('format')
        batch_op.drop_column('taille')

    # ### end Alembic commands ###
