"""empty message

Revision ID: dd10df5af10e
Revises: a4c62caeb8b7
Create Date: 2023-06-26 09:43:19.285713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd10df5af10e'
down_revision = 'a4c62caeb8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('payed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payed', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
